services:
  - type: web
    plan: free
    name: queen-anya-md
    runtime: docker
    region: Frankfurt
    branch: master
    repo: https://github.com/Ongeri-2/Anya_v2-MD.git
    #buildCommand: |
    #  apt-get update && \
    #  apt-get install -y ffmpeg && \
    #  npm install
    autoDeploy: true
    healthCheckPath: /
    #startCommand: npm start
    envVars:
      - key: BotName
        value: ""
      - key: Footer
        value: "¬© Queen Anya Bot"
      - key: Prefix
        value: "."
      - key: ThemeEmoji
        value: "üéê"
      - key: Owner_Name
        value: "Ongeri üíúüíú"
      - key: Owner_Number
        value: "254713145618"
      - key: Insta
        value: "3.69_pika"
      - key: Author
        value: "PikaBotz"
      - key: PackName
        value: "Queen Anya ‚Ä¢ Stickers"
      - key: Web
        value: "https://github.com/PikaBotz"
      - key: GcLink
        value: "https://chat.whatsapp.com/E490r0wSpSr89XkCWeGtnX"
      - key: Warn_Limits
        value: "3"
      - key: Cooldown_Timer_Seconds
        value: "5"
      - key: Port
        value: "8080"
      - key: MongoDB
        value: "YOUR_MONGODB_URL"
      - key: SESSION_ID
        value: "Wv4Qzv2Z_A_N_Y_A_V_2_Ud0e95WhCuVG"
